name: Docker
on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  docker:
    uses: zooai/.github/.github/workflows/docker-build.yml@main
    with:
      image: ghcr.io/zooai/zoo-industries
      runner-amd64: zoo-build-linux-amd64
      runner-arm64: zoo-build-linux-amd64
      runner-deploy: zoo-build-linux-amd64
      platforms: "linux/amd64"
    secrets: inherit
